name: PosFormer_3
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - abseil-cpp=20230802.0=h6a678d5_2
  - absl-py=2.1.0=pyhd8ed1ab_0
  - c-ares=1.34.5=hef5626c_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cffi=1.15.0=py38h3931269_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - cudatoolkit=10.2.89=h713d32c_10
  - cudnn=7.6.5.32=h01f27c4_1
  - fsspec=2024.10.0=pyhff2d567_0
  - future=1.0.0=pyhd8ed1ab_0
  - gmp=6.2.1=h58526e2_0
  - grpc-cpp=1.48.2=he1ff14a_4
  - grpcio=1.48.2=py38he1ff14a_4
  - gtest=1.14.0=hdb19cb5_1
  - importlib-metadata=8.5.0=pyha770c72_0
  - intel-openmp=2022.1.0=h9e868ea_3769
  - ld_impl_linux-64=2.44=h153f514_2
  - libblas=3.9.0=38_h4a7cf45_openblas
  - libcblas=3.9.0=38_h0358290_openblas
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=13.2.0=h69a702a_0
  - libgfortran5=13.2.0=ha4646dd_0
  - libgomp=11.2.0=h1234567_1
  - liblapack=3.9.0=38_h47877c9_openblas
  - libopenblas=0.3.30=h46f56fc_0
  - libprotobuf=3.20.3=he621ea3_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - magma=2.5.4=hfead8bd_4
  - markdown=3.6=pyhd8ed1ab_0
  - markupsafe=2.1.1=py38h0a891b7_1
  - mkl=2022.1.0=hc2b9512_224
  - nccl=2.14.3.1=h1a5f58c_0
  - ncurses=6.5=h7934f7d_0
  - ninja=1.11.0=h924138e_0
  - numpy=1.22.3=py38h99721a1_2
  - openssl=3.0.18=hd6dcaed_0
  - packaging=25.0=pyh29332c3_1
  - pandoc=1.19.2.1=hea2e7c5_1
  - pip=24.2=py38h06a4308_0
  - protobuf=3.20.3=py38h6a678d5_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pycparser=2.22=pyhd8ed1ab_0
  - pydeprecate=0.3.1=pyhd8ed1ab_0
  - python=3.8.20=he870216_0
  - python_abi=3.8=2_cp38
  - pytorch=1.12.1=cuda102py38hfdb21e3_200
  - pytorch-lightning=1.4.9=pyhd8ed1ab_0
  - pyyaml=6.0=py38h0a891b7_4
  - re2=2022.04.01=h27087fc_0
  - readline=8.3=hc2a1206_0
  - setuptools=75.1.0=py38h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - sleef=3.5.1=h9b69904_2
  - sqlite=3.50.2=hb25bd0a_1
  - tensorboard=2.17.1=pyhd8ed1ab_0
  - tensorboard-data-server=0.7.0=py38h52d8a92_1
  - tk=8.6.15=h54e0aa7_0
  - torchmetrics=0.6.0=pyhd8ed1ab_0
  - tqdm=4.67.1=pyhd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - werkzeug=3.0.6=pyhd8ed1ab_0
  - wheel=0.44.0=py38h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7f98852_2
  - zipp=3.21.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - click==8.1.8
      - docstring-parser==0.17.0
      - einops==0.8.1
      - importlib-resources==6.4.5
      - jinja2==3.1.6
      - jsonargparse==4.40.2
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - pillow==10.4.0
      - psutil==7.1.3
      - pygments==2.19.2
      - rich==14.2.0
      - shellingham==1.5.4
      - torchvision==0.19.1
      - typer==0.20.0
      - typeshed-client==2.7.0
prefix: /home/baoquan/miniconda3/envs/PosFormer_3
